#import ImageThumbnailFragment from './ImageThumbnailFragment.gql'

fragment ActivityLightFragment on ActivityRecord {
	__typename
	_modelApiKey
	id
	title
	blackHeadline
	image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	dateEnd
	location
	slug
}
