fragment ActivityFragment on ActivityRecord {
	__typename
	_modelApiKey
	id
	title
	blackHeadline
	image {
		...ImageFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	dateEnd
	location
	showForm
	slug
	content {
		value
		links {
			__typename
			... on LexiconRecord {
				__typename
				id
				word
				desc {
					blocks
					links
					value
				}
			}
		}
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
			... on FormRecord {
				__typename
				id
				subject
				reciever
				confirmation
				formFields {
					__typename
					... on FormTextRecord {
						id
						title
					}
					... on FormTextblockRecord {
						id
						title
					}
					... on PdfFormRecord {
						id
						title
					}
				}
			}
		}
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}
