#import "./fragments/AboutFragment.gql"

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

query AllAbouts {
	abouts: allAbouts(first: 100) {
		...AboutFragment
	}
}

query AllAboutsMenu {
	abouts: allAbouts(first: 100) {
		title
		slug
	}
}
