query Activity($slug: String!) {
	activity(filter: { slug: { eq: $slug } }) {
		...ActivityFragment
	}
}
query ActivityById($id: ItemId!) {
	activity(filter: { id: { eq: $id } }) {
		...ActivityFragment
	}
}

query AllActivities($first: IntType = 500, $skip: IntType = 0, $categoryId: ItemId) {
	allActivities(
		orderBy: [date_DESC]
		first: $first
		skip: $skip
		filter: { category: { eq: $categoryId } }
	) {
		...ActivityLightFragment
	}
	_allActivitiesMeta(filter: { category: { eq: $categoryId } }) {
		count
	}
}

query AllActivitiesForCalendar($first: IntType = 500, $skip: IntType = 0, $categoryId: ItemId) {
	allActivities(
		orderBy: [date_DESC]
		first: $first
		skip: $skip
		filter: { category: { eq: $categoryId } }
	) {
		id
		date
		dateEnd
		title
		slug
	}
	_allActivitiesMeta(filter: { category: { eq: $categoryId } }) {
		count
	}
}

query AllPastAndFutureActivities(
	$categoryId: ItemId
	$date: DateTime
	$first: IntType
	$skip: IntType
) {
	allActivities(
		filter: {
			category: { eq: $categoryId }
			OR: [
				{ date: { gt: $date }, dateEnd: { gt: $date, exists: true } }
				{ dateEnd: { lt: $date, exists: true } }
				{ date: { gt: $date } }
			]
		}
		orderBy: [date_ASC]
		first: $first
		skip: $skip
	) {
		...ActivityLightFragment
	}
	_allActivitiesMeta(
		filter: {
			category: { eq: $categoryId }
			OR: [
				{ date: { gt: $date }, dateEnd: { gt: $date, exists: true } }
				{ dateEnd: { lt: $date, exists: true } }
				{ date: { gt: $date } }
			]
		}
	) {
		count
	}
}

query AllPresentActivities($first: IntType = 100, $skip: IntType = 0, $date: DateTime) {
	allActivities(
		filter: { date: { lte: $date }, dateEnd: { gte: $date, exists: true } }
		orderBy: [date_ASC]
		first: $first
		skip: $skip
	) {
		...ActivityLightFragment
	}
	_allActivitiesMeta(filter: { date: { lte: $date }, dateEnd: { gte: $date, exists: true } }) {
		count
	}
}

query AllActivityCategories($first: IntType = 100, $skip: IntType = 0) {
	allActivityCategories(first: $first, skip: $skip) {
		id
		category
	}
}

query LatestActivities($first: IntType = 2, $skip: IntType = 0, $date: DateTime) {
	allActivities(
		filter: { dateEnd: { gte: $date } }
		orderBy: [date_ASC]
		first: $first
		skip: $skip
	) {
		...ActivityLightFragment
	}
}

fragment ActivityFragment on ActivityRecord {
	__typename
	_modelApiKey
	id
	title
	blackHeadline
	image {
		...ImageFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	dateEnd
	location
	showForm
	slug
	content {
		value
		links {
			__typename
			... on LexiconRecord {
				__typename
				id
				word
				desc {
					blocks
					links
					value
				}
			}
		}
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
			... on FormRecord {
				__typename
				id
				subject
				reciever
				confirmation
				formFields {
					__typename
					... on FormTextRecord {
						id
						title
					}
					... on FormTextblockRecord {
						id
						title
					}
					... on PdfFormRecord {
						id
						title
					}
				}
			}
		}
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}

fragment ActivityLightFragment on ActivityRecord {
	__typename
	_modelApiKey
	id
	title
	blackHeadline
	image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	dateEnd
	location
	slug
}
