query ContactPage {
	contactPage {
		title
		image {
			...ImageFragment
		}
		showImage
		intro
		content {
			links {
				__typename
				... on LexiconRecord {
					__typename
					id
					word
					desc {
						blocks
						links
						value
					}
				}
			}
			... on ContactPageModelContentField {
				blocks {
					__typename
					... on ButtonRecord {
						id
						text
						url
					}
					... on ImageRecord {
						id
						image {
							...ImageFragment
						}
						layout
					}
					... on VideoRecord {
						id
						video {
							width
							height
							provider
							providerUid
							thumbnailUrl
							title
							url
						}
					}
				}
				links {
					... on LexiconRecord {
						...LexiconFragment
					}
				}
				value
			}
			value
		}
		slug
	}
}
