query Knowledge($slug: String!) {
	knowledge(filter: { slug: { eq: $slug } }) {
		...KnowledgeFragment
	}
}
query KnowledgeById($id: ItemId!) {
	knowledge(filter: { id: { eq: $id } }) {
		...KnowledgeFragment
	}
}

query AllKnowledges($first: IntType = 500, $skip: IntType = 0) {
	allKnowledges(orderBy: [createdAt_DESC], first: $first, skip: $skip) {
		...KnowledgeLightFragment
	}
	_allKnowledgesMeta {
		count
	}
}

query AllKnowledgesFilter(
	$first: IntType = 10
	$skip: IntType = 0
	$categoryId: ItemId
	$themeIds: [ItemId]
	$lengthId: ItemId
	$seriesIds: [ItemId]
) {
	allKnowledges(
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
		filter: {
			theme: { anyIn: $themeIds }
			category: { eq: $categoryId }
			length: { eq: $lengthId }
			series: { anyIn: $seriesIds }
		}
	) {
		...KnowledgeLightFragment
	}
	_allKnowledgesMeta(
		filter: {
			theme: { anyIn: $themeIds }
			category: { eq: $categoryId }
			length: { eq: $lengthId }
			series: { anyIn: $seriesIds }
		}
	) {
		count
	}
}

query KnowledgeFilters {
	allKnowledgeThemes(first: 100) {
		__typename
		id
		title
	}
	allKnowledgeLengths(first: 100) {
		__typename
		id
		title
	}
	allKnowledgeSeries(first: 100) {
		__typename
		id
		title
	}
	allKnowledgeCategories(first: 100) {
		__typename
		id
		category
		slug
	}
}

query AllKnowledgesByCategory($categoryId: ItemId!, $first: IntType = 10, $skip: IntType = 0) {
	allKnowledges(
		filter: { category: { eq: $categoryId } }
		orderBy: [createdAt_DESC]
		first: $first
		skip: $skip
	) {
		...KnowledgeLightFragment
	}
	_allKnowledgesMeta(filter: { category: { eq: $categoryId } }) {
		count
	}
}

query AllPastAndFutureKnowledges($categoryId: ItemId, $first: IntType = 500, $skip: IntType = 0) {
	allKnowledges(filter: { category: { eq: $categoryId } }, first: $first, skip: $skip) {
		...KnowledgeLightFragment
	}
	_allKnowledgesMeta(filter: { category: { eq: $categoryId } }) {
		count
	}
}

query AllPresentKnowledges($categoryId: ItemId!, $first: IntType = 500, $skip: IntType = 0) {
	allKnowledges(filter: { category: { eq: $categoryId } }, first: $first, skip: $skip) {
		...KnowledgeLightFragment
	}
	_allKnowledgesMeta {
		count
	}
}

query AllKnowledgeCategories($first: IntType = 500, $skip: IntType = 0) {
	allKnowledgeCategories(first: $first, skip: $skip) {
		id
		category
		slug
	}
	_allKnowledgeCategoriesMeta {
		count
	}
}

fragment KnowledgeFragment on KnowledgeRecord {
	__typename
	_modelApiKey
	_createdAt
	id
	createdAt
	title
	blackHeadline
	image {
		...ImageFragment
	}
	intro(markdown: false)
	category {
		id
		category
		slug
	}
	slug
	content {
		value
		links {
			__typename
			... on LexiconRecord {
				__typename
				id
				word
				desc {
					blocks
					links
					value
				}
			}
		}
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
			... on FormRecord {
				__typename
				id
				subject
				reciever
				confirmation
				formFields {
					__typename
					... on FormTextRecord {
						id
						title
					}
					... on FormTextblockRecord {
						id
						title
					}
					... on PdfFormRecord {
						id
						title
					}
				}
			}
		}
	}
	_seoMetaTags {
		attributes
		content
		tag
	}
}

fragment KnowledgeLightFragment on KnowledgeRecord {
	__typename
	_modelApiKey
	_createdAt
	id
	createdAt
	title
	image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	category {
		id
		category
		slug
	}
	slug
}
