query Lexicon($id: ItemId!) {
	lexicon(filter: { id: { eq: $id } }) {
		...LexiconFragment
		_allReferencingActivities {
			id
			title
			slug
		}
	}
}

query AllLexicons($first: IntType = 500, $skip: IntType = 0) {
	allLexicons(first: $first, skip: $skip, orderBy: [word_ASC]) {
		...LexiconFragment
	}
	_allLexiconsMeta {
		count
	}
	lexiconText {
		intro {
			blocks
			value
			links
		}
	}
}

fragment LexiconFragment on LexiconRecord {
	__typename
	id
	word
	desc {
		blocks
		links
		value
	}
}
