query Lexicon($id: ItemId!) {
	lexicon(filter: { id: { eq: $id } }) {
		id
		word
		desc {
			blocks
			value
			links
		}
		_allReferencingActivities {
			id
			title
			slug
		}
	}
}

query AllLexicons($first: IntType = 500, $skip: IntType = 0) {
	allLexicons(first: $first, skip: $skip, orderBy: [word_ASC]) {
		id
		word
		desc {
			blocks
			value
			links
		}
	}
	_allLexiconsMeta {
		count
	}
	lexiconText {
		intro {
			blocks
			value
			links
		}
	}
}
