#import "./fragments/ImageFragment.gql"
#import "./freagments/ProjectFragment.gql"

query AllProjects {
	projects: allProjects(orderBy: [title_ASC]) {
		...ProjectFragment
	}
}

query ProjectsIntro {
	introInitiative {
		intro(markdown: false)
	}
}

query LatestProjects($first: IntType = 4, $skip: IntType = 0) {
	projects: allProjects(orderBy: [createdAt_DESC], first: $first, skip: $skip) {
		...ProjectFragment
	}
}
