#import "./fragments/ImageThumbnailFragment"

query SiteSearch(
	$activityIds: [ItemId]
	$knowledgeIds: [ItemId]
	$aboutIds: [ItemId]
	$first: IntType = 100
	$skip: IntType = 0
) {
	activities: allActivities(first: $first, skip: $skip, filter: { id: { in: $activityIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
	knowledges: allKnowledges(first: $first, skip: $skip, filter: { id: { in: $knowledgeIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		category {
			id
			category
			slug
		}
		image {
			...ImageThumbnailFragment
		}
	}
	abouts: allAbouts(first: $first, skip: $skip, filter: { id: { in: $aboutIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
}
