#import "./fragments/ImageThumbnailFragment"

query SiteSearch($activityIds: [ItemId], $first: IntType = 100, $skip: IntType = 0) {
	activities: allActivities(first: $first, skip: $skip, filter: { id: { in: $activityIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
}
