query Start {
	start {
		id
		gallery {
			id
			headline
			image {
				...ImageFragment
			}
			link {
				... on AboutRecord {
					id
					slug
					title
				}
				... on ActivityRecord {
					id
					slug
					title
				}
			}
			blackText
		}
		sections {
			__typename
			... on ImageShortcutRecord {
				id
				image {
					...ImageFragment
				}
				headline
				text
				link
			}
			... on ImageShortcutDoubleRecord {
				id
				shortcuts{
					id
					headline
					image{
						...ImageFragment
					}
					link
					text
				}
			}
			... on TextRecord {
				id
				headline
				text
				link
			}
			... on LatestActivityRecord {
				id
			}
		}
	}
}
